GET http://localhost:3000/api/etiquetas

###

//Cambiar por nombre nuevo
POST http://localhost:3000/api/etiquetas
Content-Type: application/json

{
    "nombre": "Derecho" 
}

####

//Nombre de etiqueta repetida
POST http://localhost:3000/api/etiquetas
Content-Type: application/json

{
    "nombre": "Programación" 
}

###
// Etiqueta con usuarios asociados  
DELETE http://localhost:3000/api/etiquetas/1

###

//Etiqueta con cursos asociados
DELETE http://localhost:3000/api/etiquetas/2

###

//Borrado exitoso
DELETE http://localhost:3000/api/etiquetas/20
###